name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'maintenance'

change-template: '- $TITLE (#$NUMBER)'

no-changes-template: '- No changes'

# Optionally, exclude certain labels from appearing in release notes
exclude-labels:
  - 'skip-changelog'

# Optionally, add a footer
footer: |
  _Thanks to all contributors!_
